build: off
clone_depth: 5
platform: x64
configuration: Release

environment:
    PKG_NAME: glimix_core
    PYTHON: "C:\\Python36-x64"
    ARCH: x64

install:
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/hcephes/master/install.bat', 'install-hcephes.bat')"
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/limix/hcephes/archive/0.3.1.zip', '0.3.1.zip')"
    - install-hcephes.bat
    - set PATH=%programfiles%\hcephes\bin;%PATH%
    - set LIBRARY_INC=%programfiles%\hcephes\include;%LIBRARY_INC%
    - set LIBRARY_LIB=%programfiles%\hcephes\lib;%LIBRARY_LIB%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/liknorm/master/install.bat', 'install-liknorm.bat')" && install-liknorm.bat
    - set PATH=%programfiles%\liknorm\bin;%PATH%
    - set LIBRARY_INC=%programfiles%\liknorm\include;%LIBRARY_INC%
    - set LIBRARY_LIB=%programfiles%\liknorm\lib;%LIBRARY_LIB%

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
