channels:
- conda-forge
- defaults
dependencies:
- hcephes=0.2.3=1
- liknorm=1.3.11=0
- liknorm-py=1.0.11
- libffi
- numpy
- pandas
- pip
- python=3.5
- python-dateutil
- pytz
- readline
- scipy
- setuptools
- six
- sqlite
- tk
- wheel
- xz
- zlib=1.2.11
- pip:
  - apipkg==1.4
  - brent-search==1.0.29
  - cachetools==2.0.1
  - dask==0.15.3
  - execnet==1.4.1
  - ndarray-listener==1.0.26
  - numpy-sugar==1.1.2
  - optimix==1.2.21
  - pep8==1.7.0
  - py==1.4.34
  - pytest==3.2.2
  - pytest-cache==1.0
  - pytest-pep8==1.0.6
  - pytest-sugar==0.9.0
  - scipy-sugar==1.0.4
  - sphinx-rtd-theme==0.2.4
  - termcolor==1.1.0
  - toolz==0.8.2
  - tqdm==4.18.0
