name: py35
channels:
- conda-forge
- defaults
dependencies:
- cachetools=2.0.0=py35_0
- cffi=1.7.0=py35_0
- libffi=3.2.1=3
- liknorm=1.2.3=0
- numpy-sugar=1.0.24=py35_2
- pycparser=2.17=py35_0
- scipy-sugar=1.0.1=py35_0
- tqdm=4.11.2=py35_0
- llvmlite=0.16.0=py35_0
- mkl=2017.0.1=0
- numba=0.31.0=np112py35_0
- numpy=1.12.0=py35_0
- openssl=1.0.2k=1
- pip=9.0.1=py35_1
- python=3.5.3=1
- readline=6.2=2
- scipy=0.19.0=np112py35_0
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
    sphinxcontrib-bibtex==0.3.5
